consumer:
  host: localhost
  username: fiubrother
  password: alwayswatching
  queue: analysed_video_chunks
publisher:
  host: localhost
  username: fiubrother
  password: alwayswatching
  exchange: fiubrother
  routing_key: interpolated_video_chunks
db:
  host: localhost
  database: big_fiubrother
  username: fiubrother
  password: alwayswatching
synchronization:
  host: localhost
  port: 2181
storage:
  host: localhost
  access_key: fiubrother
  secret_key: alwayswatching
interpolation_fps: 24