consumer:
  host: localhost
  username: fiubrother
  password: alwayswatching
  queue: analysed_video_chunks
db:
  host: localhost
  database: big_fiubrother
  username: fiubrother
  password: alwayswatching
synchronization:
  host: localhost
  port: 2181
storage:
  host: localhost
  port: 9500
  access_key: fiubrother
  secret_key: alwayswatching
logging:
  host: localhost
  port: 12201
interpolation_fps: 24
web_server_host: http://127.0.0.1:8080/video