consumer:
  host: localhost
  username: fiubrother
  password: alwayswatching
  queue: analysed_video_chunks
publisher:
  host: localhost
  username: fiubrother
  password: alwayswatching
  exchange: fiubrother
  routing_key: interpolated_video_chunks
db:
  host: localhost
  database: big_fiubrother_test
  username: postgres
  password: password
tmp_path: tmp
interpolation_fps: 24